<a href="https://colab.research.google.com/github/D1N2O3B4/Python_and_Numpy/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### **Assignment 2 - Numpy Array Operations**
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
>
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 .
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions.

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [93]:
!pip install jovian --upgrade -q

In [94]:
import jovian

In [95]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [96]:
import numpy as np

In [97]:
# List of functions explained
function1 = np.empty([3,3],dtype=int,order="F")
function2 = np.matrix([34,12])
function3 = np.asmatrix(np.array([34,12]))
function4 = np.linspace(5,200,num=30,endpoint=True,retstep=True,dtype=int)
function5 = np.geomspace(23,901)
function5

array([ 23.        ,  24.78779969,  26.7145658 ,  28.79110026,
        31.02904461,  33.44094532,  36.04032409,  38.84175366,
        41.86093954,  45.114808  ,  48.62160104,  52.40097857,
        56.47412871,  60.86388652,  65.59486206,  70.69357833,
        76.18861995,  82.11079348,  88.49330005,  95.37192154,
       102.78522118, 110.77475973, 119.38532847, 128.66520035,
       138.66640058, 149.44499831, 161.06142099, 173.5807931 ,
       187.07330127, 201.61458779, 217.28617464, 234.17592053,
       252.37851349, 271.99600167, 293.13836547, 315.92413411,
       340.48105015, 366.94678562, 395.46971386, 426.20974133,
       459.33920408, 495.04383392, 533.52379969, 574.99482941,
       619.68941974, 667.8581394 , 719.77103394, 775.71913964,
       836.01611516, 901.        ])

## Function 1 - np.empty([shape],dtype=`int`,order="C")

The empty function creates an array with a given shape and specific datatype.
The orders are only 2 namely C for C-style and F for Fortran-Style
The values returned here are not initiallized.

In [98]:
# Example 1 - working (change this)
# arr1 = [[1, 2],
#         [3, 4.]]

# arr2 = [[5, 6, 7],
#         [8, 9, 10]]

np.empty([2,2],dtype=int,order="C")

array([[       52777200,               0],
       [140374525740192, 140374525740192]])

Ok in this example we are setting the shape to 3 x 2 meaning we will have 2 columns and 3 rows and our dtype is float with order Fortran style

In [99]:
# Example 2 - working
np.empty([3,2],dtype=float,order="F")

array([[9.88e-324, 4.84e-322],
       [9.88e-324, 4.84e-322],
       [9.88e-324, 4.89e-322]])

In this example we are going to show the parameters the method empty need to function.

In [101]:
# Example 3 - breaking (to illustrate when it breaks)
# arr1 = [[1, 2],
#         [3, 4.]]

# arr2 = [[5, 6, 7],
#         [8, 9, 10]]

np.empty(dtype=int,order="C")

TypeError: ignored

The method above broke because we didn't specify the shape. Actually this method can work with just only the shape making the defualt settings of dtype=float and order="C"

This function is used if we want to create an array of specific shape but don't actually care about the values it contains

In [102]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - np.matrix([array])

This function turns directly inputed arrays into matrices

In [103]:
# Example 1 - working
np.matrix([[344,11],[67,5]])

matrix([[344,  11],
        [ 67,   5]])

Turning an array with a different shape into a matrix

In [104]:
# Example 2 - working
np.matrix([[5,4],[12,55],[33,89]])

matrix([[ 5,  4],
        [12, 55],
        [33, 89]])

Checking to see if we can turn 3d arrays to 3d matrices

In [106]:
# Example 3 - breaking (to illustrate when it breaks)
np.matrix([
            [[5,4],[12,55],[33,89]],
            [[13,90],[1,5],[93,81]]
            ])

ValueError: ignored

Well per the error given we can only avoid this by placing dimensions less than 3 in the function.

Some closing comments about when to use this function.

In [107]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - np.asmatrix(array)

This numpy function turns numpy arrays into matrices

In [108]:
# Example 1 - working
a = np.array([[233,122],[101,13]])

b = np.asmatrix(a)

a[0,1] = 34

b

matrix([[233,  34],
        [101,  13]])

This code below shows we can turn any shape of numpy array into a matrix

In [109]:
# Example 2 - working
c = np.array([23,12])
d = np.asmatrix(c)
c[1] = 15
d

matrix([[23, 15]])

The code below shows the function needs an array to be able to work

In [111]:
# Example 3 - breaking (to illustrate when it breaks)
e = "KK"
f = np.asmatrix(e)
f

ValueError: ignored

So the method broke because it doesn't take in single string values they need to be in a list. To fix this use either floats doubles or int or place the strings in a list.





Some closing comments about when to use this function.

In [112]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - np.linspace(
  start,stop,num=20,endpoint=True, retstep=False, dtype=None
  )
This function creates arrays which are evenly spaced out.

In [113]:
# Example 1 - working
np.linspace( 2, 99, num = 20, endpoint=False, retstep=False, dtype=int)

array([ 2,  6, 11, 16, 21, 26, 31, 35, 40, 45, 50, 55, 60, 65, 69, 74, 79,
       84, 89, 94])

In this example we will set all bool values to true

In [114]:
# Example 2 - working
np.linspace( 2, 99, num = 20, endpoint=True, retstep=True, dtype=int)

(array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 53, 58, 63, 68, 73, 78, 83,
        88, 93, 99]),
 5.105263157894737)

Endpoint being true shows the last value which is 99 and also gives out the step of each element to the next one.

In [116]:
# Example 3 - breaking (to illustrate when it breaks)
np.linspace( 2, num = 20, endpoint=False, retstep=True, dtype=int)

TypeError: ignored

We need to get a range of values. In this execution we have the start but not the stop value so it throws an error.

It is used when we want to create an array which has evenly spaced elements.

In [117]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - np.geomspace()
This is a function which creats arrays with elements forming a geometric progression.

In [118]:
# Example 1 - working
np.geomspace(2,50, num=50, endpoint= True, dtype=float,axis=0)

array([ 2.        ,  2.13579411,  2.28080823,  2.43566839,  2.60104309,
        2.77764625,  2.96624025,  3.16763922,  3.38271258,  3.6123888 ,
        3.85765935,  4.11958305,  4.3992906 ,  4.69798947,  5.01696911,
        5.35760652,  5.72137222,  6.10983653,  6.52467642,  6.96768272,
        7.44076784,  7.94597405,  8.48548227,  9.0616215 ,  9.6768789 ,
       10.33391045, 11.03555252, 11.78483401, 12.58498951, 13.4394732 ,
       14.35197382, 15.32643055, 16.36705001, 17.47832447, 18.66505119,
       19.93235316, 21.28570119, 22.73093757, 24.27430124, 25.92245475,
       27.68251303, 29.56207407, 31.56925178, 33.71271093, 36.00170465,
       38.44611429, 41.05649214, 43.84410695, 46.82099259, 50.        ])

Changing the axis to -1

In [119]:
# Example 2 - working
np.geomspace(2,50, num=50, endpoint= True, dtype=float,axis=-1)

array([ 2.        ,  2.13579411,  2.28080823,  2.43566839,  2.60104309,
        2.77764625,  2.96624025,  3.16763922,  3.38271258,  3.6123888 ,
        3.85765935,  4.11958305,  4.3992906 ,  4.69798947,  5.01696911,
        5.35760652,  5.72137222,  6.10983653,  6.52467642,  6.96768272,
        7.44076784,  7.94597405,  8.48548227,  9.0616215 ,  9.6768789 ,
       10.33391045, 11.03555252, 11.78483401, 12.58498951, 13.4394732 ,
       14.35197382, 15.32643055, 16.36705001, 17.47832447, 18.66505119,
       19.93235316, 21.28570119, 22.73093757, 24.27430124, 25.92245475,
       27.68251303, 29.56207407, 31.56925178, 33.71271093, 36.00170465,
       38.44611429, 41.05649214, 43.84410695, 46.82099259, 50.        ])

Changing the axis doesn't change the overall output

In [123]:
# Example 3 - breaking (to illustrate when it breaks)
np.geomspace(50, num=50)

TypeError: ignored

We need to specify the start and stop values

Some closing comments about when to use this function.

In [124]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


In Conclusion,
np.empty()
np.asmatrix()
np.matrix()
np.linspace()
np.geomspace()

Are all helpful functions to use in data analysis.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [125]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
